apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -nokids
namespace: minecraft-bedrock-nokids
commonLabels: 
  app: minecraft
  edition: bedrock
  env: nokids

