apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -alice
namespace: minecraft-bedrock-alice
commonLabels:
  app: minecraft
  edition: bedrock
  env: alice

patches:
  - path: deployment-patch.yaml
