apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
spec:
  selector:
    app: minecraft
    edition: bedrock
  type: NodePort
  ports:
    - protocol: TCP
      port: 19132
      targetPort: 19132